IMG_SIZE = (640, 360)
# CSRT, KCF, MEDIANFLOW, MOSSE
TRACKER_NAME = 'MEDIANFLOW'
IOU_THRESHOLD = 0.4

BBOX_AREA_MIN_TH = 150
BBOX_AREA_MAX_TH = IMG_SIZE[0] * IMG_SIZE[1] / 6
MAX_TRACKER_HEALTH = 5
PIXEL_DIFFERENCE_TH = 10
STRUCTURING_KERNEL_SHAPE = (15, 15)

DISPLAY = True
IMG_FIFO_PATH = '/home/pi/fifo_img.jpg'
LOC_FIFO_PATH = '/home/pi/fifo_loc.txt'
